### ISSUE TITLE
Notify large users of `npm-run-all` that they may want to switch

### ISSUE THREAD

**Issue by voxpelli** [bcomnes/npm-run-all2#118]
Equivalent to https://github.com/eslint-community/eslint-plugin-n/issues/100. It can be hard for users of `npm-run-all` to find out that there's a maintained fork of the project, so notifying some of them to help them out. Mostly in tandem with the work in https://github.com/eslint-community/eslint-plugin-n/issues/100.

* https://github.com/typicode/json-server/pull/1446
* https://github.com/emberjs/ember.js/pull/20523
* https://github.com/nhoizey/pack11ty/issues/544 (No PR yet)
* https://github.com/eslint-community/eslint-plugin-n/pull/124

**Comment by travi** [comment]
have you considered defining a [replacement within renovate](https://github.com/renovatebot/renovate/blob/main/lib/config/presets/internal/replacements.ts)? i added [this definition](https://github.com/form8ion/renovate-config/commit/405bcc85e8056527d669c1336c348dbcd7215d29) to my personal config, and updates of my projects have been smooth. i thought i'd check in here before contributing a similar PR to renovate itself.

in case you are not familiar with the contribution process for defining replacement definitions, here are some [examples of others i've contributed](https://github.com/renovatebot/renovate/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Atravi). in the ones that i've contributed, the original packages were deprecated, so it was easy to make it clear that the project recommended migrating to the replacement. that would be different in this case, so that might be worth a conversation with the renovate team.

**Comment by bcomnes** [comment]
That's a great idea. I wonder what they would do in this situation. Worth a shot even if it's not accepted.

**Comment by travi** [comment]
i finally got a chance to open https://github.com/renovatebot/renovate/pull/25085

**Comment by bcomnes** [comment]
Thank you for doing that @travi! I hope they accept the replacement suggestion. It would be great to get even more people benefiting from the maintenance we are doing here.

**Comment by viceice** [comment]
replacement merged and live since v37.7.0 of renovate

**Comment by voxpelli** [comment]
@viceice Yay!

**Comment by bcomnes** [comment]
About to cross 13k dependents. Thank you @travi and anyone else involved. I hope we can serve the ecosystem well! Closing as DONE!

**Comment by bcomnes** [comment]
This is closed, but I'm going to start adding a trail of PRs I open. Feel free to unsubscribe if it gets too noisy. 

https://github.com/syntaxfm/website/pull/1771

**Comment by bcomnes** [comment]
https://github.com/eslint-community/regexpp/issues/199

**Comment by Jayllyz** [comment]
https://github.com/microsoft/vscode/issues/204398
