### ISSUE TITLE
[Bug]: run fail in pnpm with read third-party config define

### ISSUE THREAD

**Issue by Gehbt** [bcomnes/npm-run-all2#150]
config define, as long as have it
![image](https://github.com/user-attachments/assets/ed35310d-7ae0-498b-9ac5-fc5ed229d578)

script define
![image](https://github.com/user-attachments/assets/d6e4e290-5950-474b-a1a7-179d04e38f4b)

run
![image](https://github.com/user-attachments/assets/e44d1fb9-0467-45d0-b16f-f1b48a859c54)

# Reproduction
https://github.com/Gehbt/nra2-bug-repo

---
In yarn or npm, It is fine.

**Comment by bcomnes** [comment]
Thank you for the report, will investigate soon.

**Comment by bcomnes** [comment]
It looks like npm-run-all2 is parsing out the special config field defined in the package.json spec:

https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true#config

and passing it as a flag in the form of:

```js
{
  execPath: '/opt/homebrew/Cellar/node/22.8.0/bin/node',
  spawnArgs: [
    '/opt/homebrew/Cellar/pnpm/9.9.0/libexec/lib/node_modules/pnpm/bin/pnpm.cjs',
    'run',
    '--nra2-bug-repo:commitizen_path=cz-conventional-changelog',
    'lint.check'
  ],
...
}
```

To be perfectly honest, I'm super unfamiliar with the config field in package.json and the various ways it gets used. Npm doesn't seem to care about it (and maybe even uses it somehow, I'm not sure). pnpm OTOH doesn't like extra fields. It looks like yarn also doesn't like the extra fields? Anyway, I'll skip adding those for pnpm as well since it clearly doesn't work when they are passing.

**Comment by bcomnes** [comment]
Try out https://github.com/bcomnes/npm-run-all2/releases/tag/v6.2.3 and please let me know if that works for you.
